<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="shailesh" failures="1" tests="4" name="UserTest" time="19.951" errors="0" timestamp="2025-08-07T19:52:13 IST">
  <testcase classname="api.test.UserTests" name="testpostuser" time="7.179"/>
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="4.007"/>
  <testcase classname="api.test.UserTests" name="testUpdateUserByUserName" time="2.419"/>
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="4.482">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testDeleteUserByName(UserTests.java:85)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
</testsuite> <!-- UserTest -->
